# config.toml
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Theme' -OlightThemeBackgroundColor=#eff1f5 -OdarkThemeBackgroundColor=#1e1e2e"
